version: "3"
services:
  php-environment:
    container_name: drinkspay
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - "8081:80"
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "9000:80" # Use port 80 for phpMyAdmin
